2025-10-22 20:59:16,321 | INFO | Main | === Iniciando Jarvis ===
2025-10-22 20:59:18,382 | INFO | Main | Respuesta a comando: Hace 25°C y soleado
2025-10-22 20:59:18,382 | ERROR | Main | Error shutting down virtual_voice
Traceback (most recent call last):
  File "c:\Users\yo\Documents\GitHub\ProBestoJarvisAI\JarvisAI\main.py", line 29, in main_loop
    procesar_comando(comando)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "c:\Users\yo\Documents\GitHub\ProBestoJarvisAI\JarvisAI\main.py", line 20, in procesar_comando
    virtual_voice.hablar(respuesta)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'modules.voz_jarvis.virtual_voice' has no attribute 'hablar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\yo\Documents\GitHub\ProBestoJarvisAI\JarvisAI\main.py", line 35, in main_loop
    virtual_voice.shutdown()
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'modules.voz_jarvis.virtual_voice' has no attribute 'shutdown'
2025-10-22 21:16:07,370 | INFO | Main | === Iniciando Jarvis ===
2025-10-22 21:16:10,382 | INFO | Main | Respuesta a comando: I didn’t understand that command.
2025-10-22 21:16:10,383 | ERROR | Main | Error shutting down virtual_voice
Traceback (most recent call last):
  File "c:\Users\yo\Documents\GitHub\ProBestoJarvisAI\JarvisAI\main.py", line 29, in main_loop
    procesar_comando(comando)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "c:\Users\yo\Documents\GitHub\ProBestoJarvisAI\JarvisAI\main.py", line 20, in procesar_comando
    virtual_voice.hablar(respuesta)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'modules.voz_jarvis.virtual_voice' has no attribute 'hablar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\yo\Documents\GitHub\ProBestoJarvisAI\JarvisAI\main.py", line 35, in main_loop
    virtual_voice.shutdown()
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'modules.voz_jarvis.virtual_voice' has no attribute 'shutdown'
2025-10-22 21:21:12,567 | INFO | Main | === Iniciando Jarvis ===
2025-10-22 21:21:19,485 | INFO | Main | Respuesta a comando: Hace 25°C y soleado
2025-10-22 21:21:19,485 | ERROR | Main | Error shutting down virtual_voice
Traceback (most recent call last):
  File "c:\Users\yo\Documents\GitHub\ProBestoJarvisAI\JarvisAI\main.py", line 29, in main_loop
    procesar_comando(comando)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "c:\Users\yo\Documents\GitHub\ProBestoJarvisAI\JarvisAI\main.py", line 20, in procesar_comando
    virtual_voice.hablar(respuesta)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'modules.voz_jarvis.virtual_voice' has no attribute 'hablar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\yo\Documents\GitHub\ProBestoJarvisAI\JarvisAI\main.py", line 35, in main_loop
    virtual_voice.shutdown()
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'modules.voz_jarvis.virtual_voice' has no attribute 'shutdown'
